# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-09 17:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone
import django_countries.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('new', 'new'), ('pending', 'pending'), ('paid', 'paid')], default='new', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('is_removed', models.BooleanField(default=False)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='date')),
                ('number', models.IntegerField(default=0, verbose_name='number')),
                ('first_name', models.CharField(max_length=200, verbose_name='first name')),
                ('last_name', models.CharField(max_length=200, verbose_name='last name')),
                ('street', models.CharField(max_length=120, verbose_name='street')),
                ('city', models.CharField(max_length=120, verbose_name='city')),
                ('state', models.CharField(max_length=120, verbose_name='state or province')),
                ('zipcode', models.CharField(max_length=120, verbose_name='postal code')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='country')),
                ('vat_number', models.CharField(blank=True, max_length=15, verbose_name='VAT number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
            ],
            options={
                'verbose_name': 'invoice',
                'ordering': ('-date', '-number'),
                'verbose_name_plural': 'invoices',
            },
            managers=[
                ('new', django.db.models.manager.Manager()),
            ],
        ),
    ]
