# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-09 13:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone
import django_countries.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('new', 'nueva'), ('pending', 'pendiente de cobro'), ('paid', 'pagada')], default='new', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('is_removed', models.BooleanField(default=False)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='fecha')),
                ('number', models.IntegerField(default=0, verbose_name='número')),
                ('first_name', models.CharField(max_length=200, verbose_name='nombre')),
                ('last_name', models.CharField(max_length=200, verbose_name='apellidos')),
                ('street', models.CharField(max_length=120, verbose_name='calle')),
                ('city', models.CharField(max_length=120, verbose_name='ciudad')),
                ('state', models.CharField(max_length=120, verbose_name='estado o provincia')),
                ('zipcode', models.CharField(max_length=120, verbose_name='cód. postal')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='pais')),
                ('vat_number', models.CharField(blank=True, max_length=15, verbose_name='NIF/CIF')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
            ],
            options={
                'verbose_name': 'factura',
                'verbose_name_plural': 'facturas',
                'ordering': ('-date', '-number'),
            },
            managers=[
                ('new', django.db.models.manager.Manager()),
            ],
        ),
    ]
