# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-10 08:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('description', models.CharField(max_length=1024, verbose_name='description')),
                ('unit', models.CharField(blank=True, max_length=1024, null=True, verbose_name='unit')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=19, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='unit price')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_entries', to='invoices.Invoice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
