# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-15 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoiceentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'cash'), ('transfer', 'bank transfer'), ('card', 'credit card'), ('paypal', 'paypal')], default='cash', max_length=10, verbose_name='payment method'),
        ),
    ]
