# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-15 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_auto_20170515_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='year'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together=set([('year', 'number')]),
        ),
    ]
