# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-15 12:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_auto_20170515_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceentry',
            options={'ordering': ('-invoice', 'position'), 'verbose_name': 'invoice entry', 'verbose_name_plural': 'invoice entries'},
        ),
        migrations.AddField(
            model_name='invoiceentry',
            name='position',
            field=models.IntegerField(default=1, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='invoiceentry',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=19, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='invoiceentry',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=19, verbose_name='unit price'),
        ),
        migrations.AlterUniqueTogether(
            name='invoiceentry',
            unique_together=set([('position', 'invoice')]),
        ),
    ]
