# Generated by Django 3.0.1 on 2019-12-31 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_auto_20170515_1437'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='invoice',
            managers=[
            ],
        ),
    ]
